### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by sushilk1991** [icoloma/react-rug-menu#1]
I am getting following error while importing Menu and MenuItem from react-rug-menu.

```javascript
import { Menu, MenuItem } from 'react-rug-menu'; 
```

Module parse failed: /Users/sushil/Documents/unacademy-frontend/node_modules/react-rug-menu/lib/main.js Unexpected token (14:13)

Do I need any particular webpack loader for this package.

**Comment by icoloma** [comment]
Your es6/jsx compiler (most likely babel) is not being applied to this dependency. You should specify your webpack loader config using `include` instead of `exclude`. Example:

```
  {
    test: /\.js$/,
    
    // include instead of exclude, so that we can use babel with react modules like react-rug-menu
    include: [ /src\/es6/, /react-rug-menu/ ],
    //exclude: /node_modules/,

    loaders: [ 'react-hot', 'babel?presets[]=react&presets[]=es2015 ],
  }
```

**Comment by sushilk1991** [comment]
Thanks @icoloma for such a quick response.
